# Generated by Django 5.0.6 on 2024-07-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
